### PR TITLE
Move values into configuration

### PR DESCRIPTION
**Pull request by ghost**
This moves hard-coded values like the CT JSON feed and the "bad CT" servers list into configuration.

### CODE REVIEW

**Comment by ghost** [comment]
I'm closing this PR, partly because I believe this code base is abandoned with no other pull requests merged ever in it's history, and partly because the author has not made any commits in over seven months. I am also closing it because I believe I've found many, many more issues with the code base and that given its status as abandoned I will resolve on my own fork.

@Fitblip if you would like me to back-port my future commits into your repository please get in contact with me (preferably as an issue on my fork) and I'll be happy to discuss bringing them back in.

**Comment by Fitblip** [comment]
> I'm closing this PR, partly because I believe this code base is abandoned with no other pull requests merged ever in it's history, and partly because the author has not made any commits in over seven months.

Hey dude, I appreciate the PR and sorry I haven't gotten around to it, I've been busy with other projects and also been traveling. 

This code base isn't "abandoned", I just haven't found a need to improve on it since it's been running extremely stable and it does exactly what I wanted it to do. 

> I am also closing it because I believe I've found many, many more issues with the code base and that given its status as abandoned I will resolve on my own fork.

Cool man, well this is an open source project, so if you want to fork it and improve it, absolutely feel free. I've looked at your fork and see what appear to me as pedantic changes around spelling and whatnot. 

What does the service not currently do that you'd like it to?

**Comment by ghost** [comment]
Thanks for responding and clarifying the projects status.

The small, pedantic commits are just from fixing things as I've explored the code trying to understand it. My biggest concern at the moment is that you haven't explicitly specified the license this code or the externally hosted minified JS is under and it would be appreciated if you could clarify this.

In terms of functionality that I would like to see, I would like to be able to filter on certificates against specific domains, and then storing and/or triggering notifications (using say, GCP PubSub, webhooks, or AWS SNS).

I'd prefer to see this all part of the one system as opposed to having a separate system that just consumed from this, and maybe have the current codebase become one application in an umbrella project containing the other functionalities so they can run under the same VM, but have some code isolation.

**Comment by Fitblip** [comment]
> My biggest concern at the moment is that you haven't explicitly specified the license this code or the externally hosted minified JS is under and it would be appreciated if you could clarify this.

Just added an MIT license to it. 

As for the frontend I've just been lazy and don't feel like cleaning it up to release /shrug. 

> In terms of functionality that I would like to see, I would like to be able to filter on certificates against specific domains, and then storing and/or triggering notifications (using say, GCP PubSub, webhooks, or AWS SNS).

That'd be super neat! I'd love other outputs other than a websocket. This is also outside the original scope, but I'll happily look at a PR.

> I'd prefer to see this all part of the one system as opposed to having a separate system that just consumed from this, and maybe have the current codebase become one application in an umbrella project containing the other functionalities so they can run under the same VM, but have some code isolation.

That I'm not really sure how to address. If you feel like taking that onus onto yourself and implementing stuff, then I'm happy to take a look.

**Comment by ghost** [comment]
Thanks for the update. I have some more time I can dedicate to this over the next few weeks, so I'll attempt to put together some code that goes in the direction of what I want and look at sending pull requests.

**Comment by ghost** [comment]
I've managed to restructure certstream into an umbrella project, splitting the REST API and fetchers into separate applications within and merged that work into [my fork's master branch](https://github.com/CaliDog/certstream-server/compare/master...tigertoes:master). There's some minor clean ups to do in that space (mostly around tests and the likes) but apart from that it appears at least in a shape that looks good to me. Your feedback on it would be appreciated.

My plan now is to make a new application that handles notifications through non-websocket channels. Initially my thinking for an MVP is to have the outbound destinations kept in `config.exs`, introduce [aws-elixir](https://github.com/aws-beam/aws-elixir) as dependency (as SNS publishing is what I care about the most), and then wire up the fetcher to push.

If you're interested in me creating a pull request for these changes, let me know and I'll set one up - my plan is to keep my fork able to merge without conflicts as much as possible.

**Pull request closed without merging**
